addpath('C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Toolkits\Controls\GCoSim\Simulink');
%addpath('C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Toolkits\Controls\Matlab');
RecurDyn='C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Bin\';
RecurDyn_CoSim='C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Toolkits\Controls\GCoSim\Simulink';
RecurDyn_model='car_ver1.rdyn';
r_temp___=size(RecurDyn_model);
RecurDyn_model_n=r_temp___(2);
Output_File='car_ver1_GCoSim1_GCoSim1';
r_temp___=size(Output_File);
Output_file_n =r_temp___(2);
GCoSim_Name='GCoSim1';
r_temp___ = size(GCoSim_Name);
GCoSim_Name_n = r_temp___(2);
if(exist([RecurDyn_model]))
  RecurDyn_inputs = 'Control_torqueL!Contro_torqueR';
  RecurDyn_outputs = 'rr_error!g1__output!g2__output!g3__output!Tm_FR!Tm_FL!yd_output';
  RecurDyn_io_ids = [  1  2  3  4  5  6  7  8  9 ];
  RecurDyn_controltimestep = 1.e-003;
  Plant_inputs = Rearrange_io( RecurDyn_inputs );
  Plant_outputs = Rearrange_io( RecurDyn_outputs );
  r_temp___=size(Plant_inputs);
  Plant_inputs_num=r_temp___(1);
  r_temp___=size(Plant_outputs);
  Plant_outputs_num=r_temp___(1);
  splited_Version__ = split(version,".");
  Matlab_version=str2double(splited_Version__(1));
  disp('');
  disp('===== RecurDyn & Matlab/SIMULINK ==========');
  disp('%%% INFO : RecurDyn plant actuators names :');
  disp([int2str([1:size(Plant_inputs,1)]'),blanks(size(Plant_inputs,1))',Plant_inputs]);
  disp('%%% INFO : RecurDyn plant sensors names :');
  disp([int2str([1:size(Plant_outputs,1)]'),blanks(size(Plant_outputs,1))',Plant_outputs]);
  disp('※ Simulink block creation commands :');
  disp('GRDClient_block: RecurDyn client simulation in active connection');
  disp('GRDClient : RecurDyn client simulation');
  disp('GRDHost : RecurDyn host simulation');
  disp('GCosim does not support Unicode strings.');
  disp( '=============================================' ) ;
% disp( '************************ Reserved Variables ************************* ' ) ;
% disp( '* Plant_inputs,Plant_outputs,RecurDyn,RecurDyn_model,RecurDyn_static*' ) ;
% disp( '* RecurDyn_inputs,RecurDyn_io_ids,RecurDyn_outputs                  *' ) ;
% disp( '* RecurDyn_controltimestep,RecurDyn_show,RecurDyn_step              *');
% disp( '************* Reserved variables can not be changed ***************** ' ) ;
  disp( ' ' ) ;
else
  disp('');
  disp('%%% ERROR : missing RecurDyn plant model file !!!');
  disp('');
end
  clear splited_Version__;
