__________________________________________________________________________________________________
RecurDyn2024 [Windows x64 System 10.2.13271.0] Analysis message file.
Copyright (C) 1997 - 2024 FunctionBay, Inc. All rights reserved.

RMD file: car_ver1_GCoSimulink_GCoSim2.rmd [Model Name: Model1]
_________________________________________________________________________________________________
Tire model is used as below
 - Tire library: RecurDyn
 - Tire model: UA Tire
_________________________________________________________________________________________________
Tire model is used as below
 - Tire library: RecurDyn
 - Tire model: UA Tire
_________________________________________________________________________________________________
Tire model is used as below
 - Tire library: RecurDyn
 - Tire model: UA Tire
_________________________________________________________________________________________________
Tire model is used as below
 - Tire library: RecurDyn
 - Tire model: UA Tire

_________________________________________________________________________________________________
GCoSim processing...


_________________________________________________________________________________________________
System Configuration Information
    No. of Generalized Coordinate                   = 51
    No. of Generalized Velocity                     = 51
    No. of Rigid Body                               = 30

Kinematic Degree of Freedom         = 50

Total array size                    = 119406
Total memory size for array         = 4 MB

Success Process: Array Structure Construction

_________________________________________________________________________________________________
Redundant Constraint Information
    There is no redundant constraint

_________________________________________________________________________________________________
RecurDyn/SOLVER Information
    DLL type Solver for Windows 64 Bit
    No. of CPU Thread = 4
    Save Solver Animation File(RAN) Option is turned on
    C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Bin\Solver\Slvcore.dll
    C:\Program Files\FunctionBay, Inc\RecurDyn 2024\Bin\Solver\Cuser.dll

_________________________________________________________________________________________________
Analysis Information
    Dynamic Analysis
    End Time                       = 15.000000000000000
    Step                           = 100
    Plot Multiplier Step Factor    = 1
    Maximum Time Step              = 1.0E-03
    Initial Time Step              = 1.0E-06
    Error Tolerance                = 5.0E-03
_________________________________________________________________________________________________
Error has occurred
GCoSim interface is not connected.
Please check the setting about Host/Client
Error CODE: 1033008028
_________________________________________________________________________________________________
Error has occurred
RecurDyn Solver has encountered a problem
